const charJson = [
  {
    title: "Cersei Lannister",
    aliases: "The Queen",
    skills: "mind games, persuasiveness & control of kingdoms.",
    src: "images/characters/cercei.jp2",
    alt: "image of an illustrated character with long blonde hair",
    id: "Cersei",
  },
  {
    title: "Arya Stark",
    aliases: "Wolf girl",
    skills: "assassination skills, changing faces & martial arts.",
    src: "images/characters/aria.jp2",
    alt: "image of an illustrated character with short hair",
    id: "Arya",
  },
  {
    title: "Jamie Lannister",
    aliases: "Kingslayer",
    skills: "warfare, swords, money & charisma.",
    src: "images/characters/jamie.jp2",
    alt: "image of an illustrated character with blonde hair",
    id: "Jamie",
  },
  {
    title: "Khal Drogo",
    aliases: "Dothraki Leader",
    skills: "most feared and strongest of the Khals, a good leader.",
    src: "images/characters/drogo.jp2",
    alt: "image of an illustrated character with a beard",
    id: "Khal",
  },
  {
    title: "Jon Snow",
    aliases: "King in the north",
    skills: "warfare, swords, riding dragons & likeability",
    src: "images/characters/jon.jp2",
    alt: "image of an illustrated character with a mustache and black hair",
    id: "Jon",
  },
  {
    title: "Melisandre",
    aliases: "The Red Woman",
    skills: "witchcraft, speaking to gods & wisdom.",
    src: "images/characters/melisandre.jp2",
    alt: "image of an illustrated character with a red dress",
    id: "Melisandre",
  },
  {
    title: "Grey Worm",
    aliases: "Master of War",
    skills: "commander of the Unsullied, warrior & loyalty.",
    src: "images/characters/worm.jp2",
    alt: "image of an illustrated character with soldier clothes.",
    id: "Grey",
  },
  {
    title: "Sansa",
    aliases: "Queen of the North",
    skills: "mind games, leading the North & Survivor.",
    src: "images/characters/sansa.jp2",
    alt: "image of an illustrated character with long red hair.",
    id: "Sansa",
  },
  {
    title: "Daenerys Targaryen",
    aliases: "Mother of Dragons",
    skills: "dragons, freeing slaves, warfare & fire.",
    src: "images/characters/dan.jp2",
    alt: "image of an illustrated character with longe white hair",
    id: "Daenerys",
  },
  {
    title: "Tyrion Lannister",
    aliases: "The Imp",
    skills: "charisma, knowledge & the hand of Daenerys Targaryen.",
    src: "images/characters/tyrion.jp2",
    alt: "image of an illustrated character with brown hair.",
    id: "Tyrion",
  },
];
